name: Deploy Azure Data Factory (PowerShell)

on:
  push:
    branches:
      - main

jobs:
  deploy_data_factory:
    runs-on: self-hosted  # Run on a Windows runner (PowerShell is pre-installed)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Az.DataFactory module
      run: |
        # Use the latest stable version
        $moduleVersion = (Invoke-WebRequest -Uri 'https://api.powershellgallery.com/v1/Packages/Az.DataFactory/Versions' -UseBasicParsing).Content | ConvertFrom-Json | Select-Object -ExpandProperty versions | Where-Object { $_.deleted -eq $false } | Sort-Object -LastVersion | Select-Object -First 1

        Install-Module Az.DataFactory -RequiredVersion $moduleVersion.version

    - name: Login to Azure
      run: |
        Connect-AzAccount -ServicePrincipal -Credential (New-Object System.Management.Automation.PSCredential (${secrets.AZURE_CLIENT_ID}, (ConvertTo-SecureString -AsPlainText -Force ${{ secrets.AZURE_CLIENT_SECRET }}))) -TenantId ${{ secrets.AZURE_TENANT_ID }}

    - name: Create Azure Data Factory (Dev)
      run: |
        $devRgName = "dev-rg"
        $devLocation = "eastus"
        $devAdfName = "datafac-dev"

        New-AzDataFactory -ResourceGroupName $devRgName -Location $devLocation -Name $devAdfName

    - name: Create Azure Data Factory (Prod)
      run: |
        $prodRgName = "prod-rg"
        $prodLocation = "eastus"  # Change location as needed
        $prodAdfName = "datafac-prod"

        New-AzDataFactory -ResourceGroupName $prodRgName -Location $prodLocation -Name $prodAdfName
