name: Deploy Azure Data Factory

on:
  push:
    branches:
      - main

jobs:
  deploy_data_factory:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: 2.26.2
      
    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      
    - name: Create Azure Data Factory (Dev)
      run: |
        
        az datafactory create --name datafac-deployd --resource-group dev-rg --location eastus

    

    - name: Create Azure Data Factory (Prod)
      run: |
        
        az datafactory create --name datafac-deployp --resource-group prod-rg --location prod-rg
